### ISSUE TITLE
Dedupe Goldsky data on GCS

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1160]
### Describe the feature you'd like to request

Import of the goldsky data into GCP needs to be deduped. 

### Describe the solution you'd like

As efficiently as possible, we should dedupe the goldsky data for any given data source.

### Describe alternatives you've considered

N/A

**Comment by ryscheng** [comment]
From Reuven

didn't even work as i was expecting... the ordering of the files is even jankier than I expected. so based on their file format... originally I thought I could take things in batches easily... because i assumed the format was 
<pipeline start time>-<unique uuid>-<batch_number>-<page_number>.parquet

Instead the format is: 
<pipeline start time>-<unique uuid>-<worker>-<checkpoint>.parquet

And ALL of the works constantly write. I'm not sure if the <checkpoint> values are consistent
like does checkpoint 0 mean the same time to all workers?
because i was originally mass importing into bigquery that way
but because the flat files also then don't have the insert_time in the value... i'd need still one more bit of info to do the merging... that being said, i have a way to do this through dbt by using bigquery _TABLE_SUFFIX special variable if i knew that the checkpoints were consistent
but not entirely certain how efficient/inefficient that merge will be if the backfill is sufficiently disparate

**Comment by ryscheng** [comment]
Current status. If we can get access to someone's database or data warehouse, we can Airbyte replicate without any of this mess. Trying to make that happen

**Comment by ravenac95** [comment]
PR: https://github.com/opensource-observer/oso/pull/1292

**Comment by ryscheng** [comment]
Follow-on work here
https://github.com/opensource-observer/oso/issues/1293
