### ISSUE TITLE
blog: before/after impact of RF

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1792]
### What is it?

Should go out before RF4 results. Also of interest to Filecoin team.

**Comment by ryscheng** [comment]
Cool! Overall I think this checks the box of does this get people excited about retrofunding. Sharing some raw high level thoughts first.

- I appreciate your early warning that correlation != causation. I think sooner rather than later we will want to nerd-snipe an academic to do a rigorous study with us https://github.com/opensource-observer/oso/issues/1761
- The section comparing the counterfactual --- why does the line of flatline in 2023-2024? Which projects are the ones that never received RF? I feel like there is probably some selection bias? We should at least explain that.
- To distribution. charts that look like bell curves. It is really hard to tell if its skewed to the right or left. The graph hides the good stuff, because values further from center have more value, but its minimized because you're counting in a histogram. Maybe some gradient coloring (red on the left, green on the right?)? at the very least we should summarize net change in subtitles
  
-
