### ISSUE TITLE
Curate the artifacts that appear on the project page

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2064]
### What is it?

For big projects, there can be millions of associated artifacts. This makes the page load on the frontend slow and can cause some API calls to timeout.
On the website project page, we should limit to just the artifacts that have been enumerated in OSSD. 
We currently have an int model that does this: `int_artifacts_in_ossd_by_project`

**Comment by ryscheng** [comment]
Summary from discussion today:
-Let's just filter out anything that's on-chain right now. The query is too large and the artifact pages are basically empty at the moment.
- In the future, when we create custom pages for deployers or custom pages for contract addresses, then we can re-introduce them to the table. For now, since linking to these pages are effectively useless, we can ignore them for now.
- In the future, we may want to create a dynamic table that does filtering and pagination correctly with our GraphQL API. That way it's not that problematic to have a table with thousands of entries. See https://github.com/opensource-observer/oso/issues/2079

Other things we considered but decided against:
- An arbitrary artifact relations table. We already do this in the events table and we shouldn't make another one
- Copying ossd as a mart. We already do this in artifactByProject, so we shouldn't copy again
- Adding a column to artifactsByProject to indicate whether it's a "derived" artifact or from oss-directory. This seems unclean
- Filtering the table by artifactType. For some projects, we want to expose important contracts (i.e. with deterministic deployments). For other projects, we want to hide contracts (e.g. Gnosis safe).

**Comment by ryscheng** [comment]
Filtering down to artifactSources in `["WWW", "TWITTER", "FARCASTER", "GITHUB", "NPM", "ANY_EVM"]`

Published in Plasmic v67.0.2
