### ISSUE TITLE
Collector => Data warehouse

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#368]
We should support writing from collectors into a data warehouse (e.g. BigQuery).

We should first check what datasets already exist, for example:
https://ghe.clickhouse.tech/
https://www.gharchive.org/
https://docs.deps.dev/bigquery/v1/index.html

It would also be awesome to do this in a way that was agnostic to which data warehouse we use.

**Comment by davidgasquez** [comment]
> It would also be awesome to do this in a way that was agnostic to which data warehouse we use

I'd reccomend checking out the open source data ingestion landscape. Toolks like Airbyte, Stitch, Dagster, and others, offer a way to ingest data in a warehouse agnostic way.

That said, for the OSO use case, I think BigQuery is an amazing choice since many datasets are already there (GitHub, Blockchain, Deps.dev, ...).

**Comment by ravenac95** [comment]
This is outdated. We are moving to using a different kind of "collector" experience through airbyte connectors.
