### ISSUE TITLE
Improve the loading UX on the project page [JS]

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#475]
When cards are loading, they should have a fixed height (per viewport) depending on whether it's an indicator or a chart. 

Currently, as the data populates, the cards expand in size. You can see it happen by reloading a project page.

![Image](https://github.com/opensource-observer/oso/assets/42869436/e5a87c66-739f-41c3-989d-84aa4af36751)

**Comment by ccerv1** [comment]
Update: there should also be a fixed width. Given that some cards load faster than other, the resizing that happens when cards load in different orders is very distracting

**Comment by ccerv1** [comment]
Update: look for something less obnoxious than spinning circles as a loading symbol. (And double check there are no more "placeholder" texts being displayed.)

**Comment by ryscheng** [comment]
2 things I did:

1. Move the spin progress bar inside the card, so that the card is always showing, reduces the shift
2. Set `ignoreLoading` inside the area charts, so that we just show "No data" until the data is ready. Then it animates.

This is already much better, we can file more issues if we have better ideas
