### ISSUE TITLE
On `max date`, the displayed start date for project stats should  equal the first event

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#524]
Currently, it shows Unix time 0

![Image](https://github.com/opensource-observer/oso/assets/42869436/0dc48cbf-a515-4bc0-bcc8-c24bff00122c)

**Comment by ryscheng** [comment]
startDate was being set to `new Date(0)` when user clicks "max".

While this is good for explicitness, it causes the date expression to fail to detect when we want to say 'Since start of project". I just set the value to `null`, which should fix the date expression, but still allow the EventDataProvider to properly fetch all data
