### ISSUE TITLE
Include activity from forked repos under certain cases

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#609]
### Describe the feature you'd like to request

While we should keep our default policy of excluding forks, there are examples of projects that have significant activity post-fork. Here is [one such example](https://github.com/opensource-observer/insights/issues/5#issue-1976581253). We should find a way to include post-fork activity under certain circumstances.

### Describe the solution you'd like

A way of indicating in an OSS Directory YAML file that a repo is a fork and its activity (post-fork) should be included as part of the parent project's activity.

### Describe alternatives you've considered

n/a

**Comment by ccerv1** [comment]
@ravenac95 something we should discuss ad explore what it might take to relink certain forks. This specific issue came up in in person convos today. [This](https://github.com/testinprod-io/op-erigon) repo is a good example -- core OP infra that comes from a fork.

**Comment by ravenac95** [comment]
@ccerv1 technically we actually have all of this data now with the github archive. The one thing we haven't done is create models that map out the _unique_ commits. That being said, depending on how the fork is maintained, that _might_ be very difficult to impossible if the commit shas/authors change but the commit's contents stay the same. The other option is to use the commit message as the way to match but that's also a heuristic at best. We don't actually get the body of the commit diff, just that a commit occurred so a precise comparison is quite difficult. 

Thoughts on any of this? I'm curious if we close this out and consider it _good enough_? Otherwise we will need to start comparing fork diffs for some of the extreme cases.

**Comment by ccerv1** [comment]
Yep, I'm happy to close this out because we now have the ability to retrieve forked data and analyzed on it on ad hoc basis. I'll let you do the honors of closing it out and assigning a cost actual (if any)
