### ISSUE TITLE
Identify stale artifacts and de-link them from projects

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#629]
Over time, we should expect things like npm and github artifacts to become stale. When these are encountered, they should be de-linked from the event data. However, they will likely still belong in OSS-D (at least until the project owner does garbage collection, which is won't be often if ever).

I'm not sure how pervasive this issue is, but my first click on 0xsplits NPM packages led to a stale link. 🤦 

![Image](https://github.com/opensource-observer/oso/assets/42869436/727adbfe-2058-44ec-a1cb-f7a4847c6b48)

**Comment by ryscheng** [comment]
Are we still able to get historical event data for these artifacts?
If so, I'm not sure the right thing to do is to unlink them. Just because a package is no longer active doesn't mean that it's not part of the project and doesn't have important historical event data.

If splits-contracts is part of the historical dataset, but they deleted the package on npm registry, I think the current behavior is working as intended?
