### ISSUE TITLE
Explore Farcaster social graph RFP

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#894]
There is an [Optimism mission proposal](https://gov.optimism.io/t/ready-to-vote-incentivize-projects-to-integrate-the-farcaster-social-graph/7403) for projects to integrate the Farcaster social graph into their apps. There is 300K OP in funding available (but will go to multiple teams). Applications are due Feb 21 if we want to apply. 

An app related to linking Farcaster IDs to GitHub so we could join the two social graphs would be very cool. Perhaps this could be:

- Attestation app to link Github to farcaster (and wallet address)
- Frame to star or follow a repo
- Farcaster graph in OSO

Anyway, let me know what you think @ryscheng @ravenac95 and if you want to go for this.

**Comment by ryscheng** [comment]
Ya there's some cool things we could probably do. The example of "Farcaster toolkit" is probably the most related one to us. 

Relatedly, I think it's about time we introduce a new entity to the OSO schema, a user.
Similar to a "Project", we link a bunch of artifacts that are related to a user (e.g. GIT_USER, FARCASTER_ACCOUNT, EOA_ADDRESS), which could allow us to do similarly interesting analytics over public datasets of users.

Unlike oss-directory, it'd be really nice if we could just mine other public ways that users already link their profiles
e.g. ENS, GitHub profiles, Twitter profiles, Farcaster profiles
I'd rather than do any kind of attestation mechanism ourselves or via crowdsourcing, since that could be viewed as doxxing in certain contexts.

Once you have this user graph, we could make it easy to do queries of public activity.
i.e. I want to airdrop NFTs to developers who are posting to these channels on Farcaster, who contributed to these repos and deployed contracts that generate this amount of on-chain activity.

The Frame to star/follow a repo is also a cool idea (https://github.com/opensource-observer/oso/issues/804), but not sure how relevant that is to this RFP. 

@ccerv1 are you free to sync up on next steps here?

**Comment by ccerv1** [comment]
Going to close this out -- I just don't think we have the bandwidth to work on it right now.
